openapi: "3.0.0"

info:
  title: YouCorrectMaya
  description: 
  contact:
    name: Maroi LABIODH
    email: labiodhmaroi@gmail.com
  license:
    name: 
    url: 
  version: ""

tags:
  - name: corpus
    description: corpus CRUD

paths:
  /corpus:
    get:
      description:  
      tags:
        - corpus
      responses:
        '200':
          description: 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#//Error'

    post:
      description: Creates a new user
      tags:
       - user
      requestBody:
        description: New user to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        '201':
          description: New user was created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

